name: CMake-Cross-Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
  
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
  
    runs-on: ${{matrix.platform}}

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Packages
      uses: ConorMacBride/install-package@v1.1.0
      with:
        # Packages to install with brew on macOS
        brew: openssl@1.1
        # Packages to install with choco on Windows
        choco: openssl
        # Packages to install with apt on Linux
        apt: libssl-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev wayland-protocols libwayland-dev libxkbcommon-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev

    - if: runner.os == 'macOS'
      run: |
        brew --prefix openssl@1.1
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DOPENSSL_ROOT_DIR=$(brew --prefix openssl@1.1)

    - if: runner.os == 'Linux' || runner.os == 'Windows'
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.platform}}
        path: |
          build
